export const images = {
  bar: require("./assets/images/bar.jpg"),
  events: require("./assets/images/events.jpg"),
  single_room: require("./assets/images/single-room.jpg"),
  double_room: require("./assets/images/double-room.jpg"),
  suites_room: require("./assets/images/suites-room.jpg"),
  spa: require("./assets/images/spa.jpg"),
  lobi: require("./assets/images/lobi.jpg"),
  hotelback: require("./assets/images/hotelback.jpg"),
  exit_shift: require("./assets/images/logout.png"),
  enter_shift: require("./assets/images/login.png"),
  tasks: require("./assets/images/taskboard.png"),
  add_charge: require("./assets/images/creditcardpay.png"),
  reports: require("./assets/images/graphreport.png"),
  lobi: require("./assets/images/lobi.jpg"),
  workers_management: require("./assets/images/managementworkers.png"),
  shift: require("./assets/images/Shift.jpg"),
  checkIn: require("./assets/images/CheckIn.jpg"),
  checkOut: require("./assets/images/CheckOut.jpg"),
  plus: require("./assets/images/Plus.png"),
  save:require("./assets/images/Save.png"),
  edit:require("./assets/images/Edit.png"),
  trashCan:require("./assets/images/Trashcan.jpg"),
  check:require("./assets/images/Check.png"),
  calendar:require("./assets/images/calendar.png"),
  clock:require("./assets/images/clock.png"),
  waterbottle:require("./assets/images/waterbottle.png"),
  whisky:require("./assets/images/whisky.png"),
  cocacola:require("./assets/images/cocacola.png"),
  choclatebar:require("./assets/images/choclatebar.png"),
  alcoholWine:require("./assets/images/alcoholWine.png"),
  hotelloby:require("./assets/images/hotellobby.png"),
  back:require("./assets/images/back.png"),
  fadeloby:require("./assets/images/fadeloby.png"),
}